plugins {
    id "org.jetbrains.kotlin.multiplatform"
}

apply from: rootProject.file('gradle/mpp-common.gradle')
apply from: rootProject.file('gradle/mpp-ios.gradle')
apply from: rootProject.file('gradle/mpp-jvm.gradle')
apply from: rootProject.file('gradle/mpp-js.gradle')
apply from: rootProject.file('gradle/publish.gradle')

kotlin {
    abiValidation {
        enabled = true
    }

    sourceSets {
        jvmMain {
            dependencies {
                implementation "com.fasterxml.jackson.core:jackson-core:2.21.2"
                implementation "com.fasterxml.jackson.core:jackson-databind:2.21.2"
                implementation "com.fasterxml.jackson.core:jackson-annotations:2.21"
                implementation "com.fasterxml.jackson.module:jackson-module-kotlin:2.21.2"
            }
        }
        jvmTest {
            dependencies {
                implementation "org.mockito:mockito-core:5.23.0"
                implementation "junit:junit:4.13.2"
                implementation kotlin('test')
                implementation kotlin('test-junit')
            }
        }

    }

}
